ORDER BY SOURCE_REFERENCE_TRANSACTION_ID DESC

select
	    SOURCE_REFERENCE_TRANSACTION_ID,
		TRANSACTION_DATE,
		BUSINESS_DATE,
		SOURCE_PROCESSED_DATE,
		RINGING_STORE,
		TRANSACTION_TYPE,
		TRANSACTION_REVERSAL_CODE ,
		SOURCE_REFERENCE_LINE_TYPE,
		SOURCE_REFERENCE_LINE_ID,
		TRANSACTION_LINE_TYPE,
		DEPARTMENT_ID,
		CLASS_ID,
		LINE_ITEM_AMOUNT,
		TAX_AMOUNT,
		FULFILLMENT_TYPE_DROPSHIP_CODE ,
		EMPLOYEE_DISCOUNT_AMOUNT,
		STORE_OF_INTENT,
		WAIVED_REASON_CODE,
		WAIVED_AMOUNT,
		FEE_CODE,
		CASH_DISBURSEMENT_LINE1,
		CASH_DISBURSEMENT_LINE2,
		TENDER_AMOUNT,
		TENDER_TYPE ,
		TENDER_CARD_TYPE,
		TENDER_CARD_SUBTYPE,
		TENDER_ENTRY_METHOD,
		TENDER_ACTIVITY_CODE,
		DATA_SOURCE_CODE
from
	(
	select
		SOURCE_REFERENCE_TRANSACTION_ID,
		TRANSACTION_DATE,
		BUSINESS_DATE,
		SOURCE_PROCESSED_DATE,
		RINGING_STORE,
		TRANSACTION_TYPE,
		TRANSACTION_REVERSAL_CODE ,
		SOURCE_REFERENCE_LINE_TYPE,
		SOURCE_REFERENCE_LINE_ID,
		TRANSACTION_LINE_TYPE,
		DEPARTMENT_ID,
		CLASS_ID,
		LINE_ITEM_AMOUNT,
		TAX_AMOUNT,
		FULFILLMENT_TYPE_DROPSHIP_CODE ,
		EMPLOYEE_DISCOUNT_AMOUNT,
		STORE_OF_INTENT,
		WAIVED_REASON_CODE,
		WAIVED_AMOUNT,
		FEE_CODE,
		CASH_DISBURSEMENT_LINE1,
		CASH_DISBURSEMENT_LINE2,
		TENDER_AMOUNT,
		TENDER_TYPE ,
		TENDER_CARD_TYPE,
		TENDER_CARD_SUBTYPE,
		TENDER_ENTRY_METHOD,
		TENDER_ACTIVITY_CODE,
		DATA_SOURCE_CODE
	from
		(
		select
			CAST('SOURCE_REFERENCE_TRANSACTION_ID' AS VARCHAR(128)) as SOURCE_REFERENCE_TRANSACTION_ID,
			CAST('TRANSACTION_DATE' AS VARCHAR(128)) as TRANSACTION_DATE,
			CAST('BUSINESS_DATE' AS VARCHAR(128)) as BUSINESS_DATE,
			CAST('SOURCE_PROCESSED_DATE' AS VARCHAR(128)) as SOURCE_PROCESSED_DATE,
			CAST('RINGING_STORE' AS VARCHAR(128)) as RINGING_STORE,
			CAST('TRANSACTION_TYPE' AS VARCHAR(128)) as TRANSACTION_TYPE,
			CAST('TRANSACTION_REVERSAL_CODE' AS VARCHAR(128)) as TRANSACTION_REVERSAL_CODE ,
			CAST('SOURCE_REFERENCE_LINE_TYPE' AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_TYPE,
			CAST('SOURCE_REFERENCE_LINE_ID' AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_ID,
			CAST('TRANSACTION_LINE_TYPE' AS VARCHAR(128)) as TRANSACTION_LINE_TYPE,
			CAST('DEPARTMENT_ID' AS VARCHAR(128)) as DEPARTMENT_ID,
			CAST('CLASS_ID' AS VARCHAR(128)) as CLASS_ID,
			CAST('LINE_ITEM_AMOUNT' AS VARCHAR(128)) as LINE_ITEM_AMOUNT,
			CAST('TAX_AMOUNT' AS VARCHAR(128)) as TAX_AMOUNT,
			CAST('FULFILLMENT_TYPE_DROPSHIP_CODE' AS VARCHAR(128)) as FULFILLMENT_TYPE_DROPSHIP_CODE ,
			CAST('EMPLOYEE_DISCOUNT_AMOUNT' AS VARCHAR(128)) as EMPLOYEE_DISCOUNT_AMOUNT,
			CAST('STORE_OF_INTENT' AS VARCHAR(128)) as STORE_OF_INTENT,
			CAST('WAIVED_REASON_CODE' AS VARCHAR(128)) as WAIVED_REASON_CODE,
			CAST('WAIVED_AMOUNT' AS VARCHAR(128)) as WAIVED_AMOUNT,
			CAST('FEE_CODE' AS VARCHAR(128)) as FEE_CODE,
			CAST('CASH_DISBURSEMENT_LINE1' AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE1,
			CAST('CASH_DISBURSEMENT_LINE2' AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE2,
			CAST('TENDER_AMOUNT' AS VARCHAR(128)) as TENDER_AMOUNT,
			CAST('TENDER_TYPE' AS VARCHAR(128)) as TENDER_TYPE ,
			CAST('TENDER_CARD_TYPE' AS VARCHAR(128)) as TENDER_CARD_TYPE,
			CAST('TENDER_CARD_SUBTYPE' AS VARCHAR(128)) as TENDER_CARD_SUBTYPE,
			CAST('TENDER_ENTRY_METHOD' AS VARCHAR(128)) as TENDER_ENTRY_METHOD,
			CAST('TENDER_ACTIVITY_CODE' AS VARCHAR(128)) as TENDER_ACTIVITY_CODE,
			CAST('DATA_SOURCE_CODE' AS VARCHAR(128)) as DATA_SOURCE_CODE) as header_row
union all
	select
		CAST(SLS_TRN_HDR_OPR.SLS_TRAN_OPR_NUM AS VARCHAR(128)) as SOURCE_REFERENCE_TRANSACTION_ID,
		CAST(SCH_TRANS_DT AS VARCHAR(128)) as TRANSACTION_DATE,
		CAST(SLS_TRN_HDR_OPR.SCH_BUS_DAY_DT AS VARCHAR(128)) as BUSINESS_DATE,
		CAST(SLS_TRN_HDR_OPR.PROCESS_DT AS VARCHAR(128)) as SOURCE_PROCESSED_DATE,
		CAST(CAST(SLS_TRN_HDR_OPR.SCH_RTL_STOR_NUM AS BIGINT) AS VARCHAR(128)) as RINGING_STORE,
		CAST(SI_TRANS_TYP_CD AS VARCHAR(128)) as TRANSACTION_TYPE,
		CAST(SCH_TRANS_RVRSL_CD AS VARCHAR(128)) as TRANSACTION_REVERSAL_CODE ,
		CAST('ItemLine' AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_TYPE,
		CAST(DTL_LN_SEQ_NUM AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_ID,
		CAST(DTL_ACTV_TYP_CD AS VARCHAR(128)) as TRANSACTION_LINE_TYPE,
		CAST(DTL_POS_DEPT_ID AS VARCHAR(128)) as DEPARTMENT_ID,
		CAST(DTL_POS_CLS_ID AS VARCHAR(128)) as CLASS_ID,
		CAST(DTL_AMT AS VARCHAR(128)) as LINE_ITEM_AMOUNT,
		CAST(DTL_TAX_AMT AS VARCHAR(128)) as TAX_AMOUNT,
		CAST(DTL_FULFILL_TYP_CD AS VARCHAR(128)) as FULFILLMENT_TYPE_DROPSHIP_CODE ,
		CAST(DTL_EMP_DISC_AMT AS VARCHAR(128)) as EMPLOYEE_DISCOUNT_AMOUNT,
		CAST(DTL_INTENT_STOR_ID AS VARCHAR(128)) as STORE_OF_INTENT,
		CAST(DTL_PSTG_WAIVED_RSN_CD AS VARCHAR(128)) as WAIVED_REASON_CODE,
		CAST(DTL_WAIVED_PSTG_AMT AS VARCHAR(128)) as WAIVED_AMOUNT,
		CAST(DTL_FEE_TYP_CD AS VARCHAR(128)) as FEE_CODE,
		CAST(CD_GL_ACCT_NUM AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE1,
		CAST(CD_GL_DEPT_ID AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE2,
		CAST(NULL AS VARCHAR(128)) as TENDER_AMOUNT,
		CAST(NULL AS VARCHAR(128)) as TENDER_TYPE ,
		CAST(NULL AS VARCHAR(128)) as TENDER_CARD_TYPE,
		CAST(NULL AS VARCHAR(128)) as TENDER_CARD_SUBTYPE,
		CAST(NULL AS VARCHAR(128)) as TENDER_ENTRY_METHOD,
		CAST(NULL AS VARCHAR(128)) as TENDER_ACTIVITY_CODE,
		CAST(DATA_SRC_CD AS VARCHAR(128)) as DATA_SOURCE_CODE
	from
		TST02_AW_VWS.SLS_TRN_HDR_OPR,
		TST02_AW_VWS.sls_trn_dtl_opr
	where
		SLS_TRN_HDR_OPR.SLS_TRAN_OPR_NUM = sls_trn_dtl_opr.SLS_TRAN_OPR_NUM
        and SI_TRANS_TYP_CD not in ('VOID', 'PAID', 'REFU')
        and SATI_TRANS_STS_CD <> 'D'
        and DATA_SRC_CD <> 'RPOS'
        and NOT EXISTS ( SELECT 1 FROM TST02_AW_VWS.SLS_TRN_HDR_OPR as V where
            SLS_TRN_HDR_OPR.SCH_RTL_STOR_NUM = V.VAI_RTL_STOR_ID
            and SLS_TRN_HDR_OPR.SCH_WRKSTTN_NUM = V.VAI_WRKSTTN_ID
            and SLS_TRN_HDR_OPR.SCH_WRKSTTN_TRAN_NUM = V.VAI_TRANS_NUM
            and SLS_TRN_HDR_OPR.SCH_BUS_DAY_DT = V.SCH_BUS_DAY_DT
        )
		and SLS_TRN_HDR_OPR.PROCESS_DT = CURRENT_DATE() - INTERVAL '2323' DAY
		and sls_trn_dtl_opr.PROCESS_DT = CURRENT_DATE() - INTERVAL '2323' DAY
union all
	select
		CAST(SLS_TRN_HDR_OPR.SLS_TRAN_OPR_NUM AS VARCHAR(128)) as SOURCE_REFERENCE_TRANSACTION_ID,
		CAST(SCH_TRANS_DT AS VARCHAR(128)) as TRANSACTION_DATE,
		CAST(SLS_TRN_HDR_OPR.SCH_BUS_DAY_DT AS VARCHAR(128)) as BUSINESS_DATE,
		CAST(SLS_TRN_HDR_OPR.PROCESS_DT AS VARCHAR(128)) as SOURCE_PROCESSED_DATE,
		CAST(CAST(SLS_TRN_HDR_OPR.SCH_RTL_STOR_NUM AS BIGINT) AS VARCHAR(128)) as RINGING_STORE,
		CAST(SI_TRANS_TYP_CD AS VARCHAR(128)) as TRANSACTION_TYPE,
		CAST(SCH_TRANS_RVRSL_CD AS VARCHAR(128)) as TRANSACTION_REVERSAL_CODE ,
		CAST('Tender' AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_TYPE,
		CAST(TI_TNDR_LN_SEQ_NUM AS VARCHAR(128)) as SOURCE_REFERENCE_LINE_ID,
		CAST(NULL AS VARCHAR(128)) as TRANSACTION_LINE_TYPE,
		CAST(NULL AS VARCHAR(128)) as DEPARTMENT_ID,
		CAST(NULL AS VARCHAR(128)) as CLASS_ID,
		CAST(NULL AS VARCHAR(128)) as LINE_ITEM_AMOUNT,
		CAST(NULL AS VARCHAR(128)) as TAX_AMOUNT,
		CAST(NULL AS VARCHAR(128)) as FULFILLMENT_TYPE_DROPSHIP_CODE,
		CAST(NULL AS VARCHAR(128)) as EMPLOYEE_DISCOUNT_AMOUNT,
		CAST(NULL AS VARCHAR(128)) as STORE_OF_INTENT,
		CAST(NULL AS VARCHAR(128)) as WAIVED_REASON_CODE,
		CAST(NULL AS VARCHAR(128)) as WAIVED_AMOUNT,
		CAST(NULL AS VARCHAR(128)) as FEE_CODE,
		CAST(NULL AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE1,
		CAST(NULL AS VARCHAR(128)) as CASH_DISBURSEMENT_LINE2,
		CAST(TI_AMT AS VARCHAR(128)) as TENDER_AMOUNT,
		CAST(TI_TNDR_TYP AS VARCHAR(128)) as TENDER_TYPE,
		CAST(TI_CARD_TYP AS VARCHAR(128)) as TENDER_CARD_TYPE,
		CAST(TI_CARD_SUB_TYP_CD AS VARCHAR(128)) as TENDER_CARD_SUBTYPE,
		CAST(TI_TNDR_ENTRY_METH_CD AS VARCHAR(128)) as TENDER_ENTRY_METHOD,
		CAST(TI_NGC_ACTV_CD AS VARCHAR(128)) as TENDER_ACTIVITY_CODE,
		CAST(DATA_SRC_CD AS VARCHAR(128)) as DATA_SOURCE_CODE
	from
		TST02_AW_VWS.SLS_TRN_HDR_OPR,
		TST02_AW_VWS.sls_trn_tndr_opr
	where
		SLS_TRN_HDR_OPR.SLS_TRAN_OPR_NUM = sls_trn_tndr_opr.SLS_TRAN_OPR_NUM
        and SI_TRANS_TYP_CD not in ('VOID', 'PAID', 'REFU')
        and SATI_TRANS_STS_CD <> 'D'
        and DATA_SRC_CD <> 'RPOS'
        and NOT EXISTS ( SELECT 1 FROM TST02_AW_VWS.SLS_TRN_HDR_OPR as V where
            SLS_TRN_HDR_OPR.SCH_RTL_STOR_NUM = V.VAI_RTL_STOR_ID
            and SLS_TRN_HDR_OPR.SCH_WRKSTTN_NUM = V.VAI_WRKSTTN_ID
            and SLS_TRN_HDR_OPR.SCH_WRKSTTN_TRAN_NUM = V.VAI_TRANS_NUM
            and SLS_TRN_HDR_OPR.SCH_BUS_DAY_DT = V.SCH_BUS_DAY_DT
        )
		and SLS_TRN_HDR_OPR.PROCESS_DT = CURRENT_DATE() - INTERVAL '2323' DAY
		and sls_trn_tndr_opr.PROCESS_DT = CURRENT_DATE() - INTERVAL '2323' DAY
) as dataRow
